name       : kicad-symbols
version    : 5.1.2
release    : 3
source     :
    - https://github.com/KiCad/kicad-symbols/archive/5.1.2.tar.gz : e89fc4d2ad27a287a9d8924e6c6c4837d39f2a7192797b8c31535ffb18f2dc8c
license    : CC-BY-SA-4.0
component  : office
summary    : Official KiCad schematic symbol libraries
description: |
    Official KiCad schematic symbol libraries.
replaces   :
    - kicad-library
setup      : |
    %cmake
install    : |
    %make_install
