name       : kicad-symbols
version    : 5.1.6
release    : 4
source     :
    - https://github.com/KiCad/kicad-symbols/archive/5.1.6.tar.gz : c4cd711698aaa681693a733f80c371e140c2cd5809e3ee569320e843aac3325e
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : Official KiCad schematic symbol libraries
description: |
    Official KiCad schematic symbol libraries.
setup      : |
    %cmake
install    : |
    %make_install
