name       : kicad-symbols
version    : 7.0.6
release    : 6
source     :
    - https://gitlab.com/kicad/libraries/kicad-symbols/-/archive/7.0.6/kicad-symbols-7.0.6.tar.gz : a5cdf6139837e9a34d0ef4089928b2fc9b865754f65c11af35eaf4cce1eaca3b
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : Official KiCad schematic symbol libraries
description: |
    Official KiCad schematic symbol libraries.
setup      : |
    %cmake
install    : |
    %make_install
