name       : kicad-symbols
version    : 5.0.0
release    : 2
source     :
    - https://github.com/KiCad/kicad-symbols/archive/5.0.0.tar.gz : 0bf931ffa8da438cf44c2b0a69c3625296e5c9935c40cd6274182cad7fcda825
license    : CC-BY-SA-4.0
component  : office
summary    : Official KiCad schematic symbol libraries
description: |
    Official KiCad schematic symbol libraries.
replaces   :
    - kicad-library
setup      : |
    %cmake
install    : |
    %make_install
